---
abstract: 'Comprehensive, flexible system for validating and parsing input, mainly targeted at web applications.'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Brannigan
requires:
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/ido50/Brannigan
  repository: https://github.com/ido50/Brannigan.git
version: 1.1
